export const testData = [
  'Aerospace',
  'Accounting',
  'Activism',
  'Advertising',
  'Aesthetics',
  'Aging',
  'Ancient History',
  'Animal Rights',
  'Anthropology',
  'Architecture',
  'Art',
  'Artificial Intelligence',
  'Astrology',
  'Agriculture',
  'Agriculture Sustainability',
  'Aviation',
  'Automotive',
  'Augmented Reality',
  'Biotech',
  'Beauty',
  'Beverages',
  'Blockchain',
  'Books',
  'Business',
  'Career',
  'Career Development',
  'Childcare',
  'Coffee',
  'Construction',
  'Console Platforms',
  'Cooking',
  'Country',
  'Cross-Cultural Communication',
  'Culture',
  'Current Events',
  'Customer Service',
  'Data Science',
  'Decision Making',
  'Design History',
  'Disability',
  'Disaster Response',
  'DIY',
  'Elderly Care',
  'Education',
  'Energy',
  'Engineering',
  'Entertainment',
  'Environment',
  'Environmental Ethics',
  'Environmentalism',
  'Epistemology',
  'Ethics',
  'Family',
  'Fashion',
  'Farming',
  'Fine Arts',
  'Fitness',
  'Fitness Technology',
  'Food',
  'Gaming',
  'Gender',
  'Gerontology',
  'Globalization',
  'Graphic Design',
  'Health',
  'Health Technology',
  'Healthy Eating',
  'Healthcare',
  'Historical Events',
  'History',
  'Home Improvement',
  'Homelessness',
  'Hospitality',
  'Hotel',
  'Human Resources',
  'Humanitarianism',
  'Indoor Activities',
  'Insurance',
  'Interior Design',
  'International Relations',
  'Journalism',
  'Job Searching',
  'Justice',
  'Language Learning',
  'Leadership',
  'LGBTQIA Rights',
  'Linguistics',
  'Logic',
  'Logistics',
  'Machine Learning',
  'Maritime',
  'Marketing',
  'Marketplace',
  'Media',
  'Metaphysics',
  'Mindfulness',
  'Mental Health',
  'Meditation',
  'Modern History',
  'Morale',
  'Movies',
  'Music',
  'Mythology',
  'Nature',
  'NGO',
  'Nutrition',
  'Online Communities',
  'Online Learning',
  'Parenting',
  'Performing Arts',
  'Personal Development',
  'Philanthropy',
  'Philosophy',
  'Photography',
  'Pharmaceuticals',
  'Pop Culture',
  'Product Design',
  'Productivity',
  'Project Management',
  'Psychology',
  'Public Relations',
  'Publishing',
  'Real Estate',
  'Relationships',
  'Religion',
  'Renewable Energy',
  'Reporting',
  'Robotics',
  'Sales',
  'Science',
  'Self Care',
  'Self-Improvement',
  'Sexuality',
  'Social Issues',
  'Social Justice',
  'Social Media',
  'Social Entrepreneurship',
  'Society',
  'Space Exploration',
  'Spirituality',
  'Sports',
  'Sports Nutrition',
  'Startups',
  'Sustainability',
  'Teaching',
  'Teamwork',
  'Technology',
  'Technology Gadgets',
  'Tourism',
  'Transportation',
  'Travel',
  'Travel Destinations',
  'TV Shows',
  'User Experience',
  'Urban Planning',
  'Video Games',
  'Virtual Assistants',
  'Virtual Reality',
  'Volunteering',
  'Waste',
  'Web Design',
  'Womens Rights',
  'Writing',
  'Zoology',
]; 
